// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjlJPJAIQOWNzx8wh0QpMN-07w5-2jO5w',
    appId: '1:610968381992:web:fd1f38fe2d756fd074631d',
    messagingSenderId: '610968381992',
    projectId: 'proxserv-hackathon',
    authDomain: 'proxserv-hackathon.firebaseapp.com',
    storageBucket: 'proxserv-hackathon.firebasestorage.app',
    measurementId: 'G-9HF5ZG2HXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAttuNofibLHltI8s3R3GBWYsiU4ChfYDY',
    appId: '1:610968381992:android:06ba34cb7367607274631d',
    messagingSenderId: '610968381992',
    projectId: 'proxserv-hackathon',
    storageBucket: 'proxserv-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcdQy5fm2i_IUHof7aw7jAFrSELs7sOwQ',
    appId: '1:610968381992:ios:418a901bd3b7aca574631d',
    messagingSenderId: '610968381992',
    projectId: 'proxserv-hackathon',
    storageBucket: 'proxserv-hackathon.firebasestorage.app',
    iosBundleId: 'com.proxserv.proxserv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcdQy5fm2i_IUHof7aw7jAFrSELs7sOwQ',
    appId: '1:610968381992:ios:418a901bd3b7aca574631d',
    messagingSenderId: '610968381992',
    projectId: 'proxserv-hackathon',
    storageBucket: 'proxserv-hackathon.firebasestorage.app',
    iosBundleId: 'com.proxserv.proxserv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjlJPJAIQOWNzx8wh0QpMN-07w5-2jO5w',
    appId: '1:610968381992:web:a14aa36fd0c8bdd574631d',
    messagingSenderId: '610968381992',
    projectId: 'proxserv-hackathon',
    authDomain: 'proxserv-hackathon.firebaseapp.com',
    storageBucket: 'proxserv-hackathon.firebasestorage.app',
    measurementId: 'G-TC0M98H705',
  );
}
